### ISSUE TITLE
Allow emit without argument

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#129]
Currently, events are emitted on `HasEvents` objects using: `x.emit('foo', {'more': 1, 'info': 2})`. But when there is no extra info (the occurrence of the event is all that's needed), one needs to write `x.emit('foo', {})`. Similarly, emitters need to return a dict, even if it is empty.

Proposed is:
* allow `x.emit('foo')`
* allow an emitter to return `None`.

**Comment by almarklein** [comment]
I don't like the idea of an emitter returning None. I think its better to be explicit here. Also because people might just have forgotten to return the correct object in one of the code paths in an emitter.

I feel less strongly about `x.emit('foo')`, but in retrospect I am leaning towards not allowing it, in sake of explicitness (you're emitting a event, which is always dict, this one happens to be empty).

cc @korijn how strongly do you feel for this?

**Comment by Korijn** [comment]
I'm used to frameworks (jQuery, Django) where the event metadata is optional. In jQuery the framework generates an Event object `e` that is passed to handlers. If the event was triggered with any additional data when emitting the event, those are exposed through `e.data`. I personally enjoy that style very much, since the framework takes care of constructing the event object, setting the `e.sender` correctly and invoking any callbacks. Event "metadata" is then always optional, both to send and to use in a handler. In Django event metadata is represented through `**kwargs`. What I also like about Django's event's is that they're not strings but types, making refactoring operations easy. But that's not compatible with flexx's dynamism, and a different story entirely. :)

Some interesting docs to compare with:

* jQuery's `Event` object: http://api.jquery.com/category/events/event-object/
* jQuery event handler using `event.data`: http://api.jquery.com/event.data/
* jQuery's `trigger` method with optional data: http://api.jquery.com/trigger/
* Django signal receiver with optional `**kwargs`: https://docs.djangoproject.com/en/1.9/topics/signals/#receiver-functions
* Django signal sender with optional `**kwargs`: https://docs.djangoproject.com/en/1.9/topics/signals/#sending-signals

**Comment by almarklein** [comment]
Closed by #130
