### ISSUE TITLE
Initial event for properties is only send to handlers of same object

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#146]
```python

from flexx import event

class Foo1(event.HasEvents):
    
    @event.prop
    def bar(self, v=0):
        return v
    
    @event.connect('bar')
    def on_bar(self, *events):
        print('Foo1 saw bar change')
    
class Foo2(event.HasEvents):
    
    def __init__(self):
        self.x = Foo1()
        super().__init__()
    
    @event.connect('x.bar')
    def on_bar(self, *events):
        print('Foo2 saw bar change')

>>> f = Foo2()
Foo1 saw bar change
>>> f.x.bar = 3
Foo1 saw bar change
Foo2 saw bar change
```

This was initially somewhat intended. Or at least a consequence of how the initialization worked, which at the time seemed acceptable. But I just ran into this and banged my head into the wall, so I now consider it a bug.

The point is that each object sends initial events at the end of initialization. But `x` does that at a time when the handlers of `f` are not yet connected. Maybe it makes sense to have each object check all handlers and create initial events for itself when such a handler is attached to a property.

**Comment by Korijn** [comment]
The "cycle" here could also use some documentation; taking a composed widget with a super- and subclass as an example might be a good use-case to demonstrate in which order properties are set and `init()`s are called?

**Comment by Korijn** [comment]
We just hit this one as well (after a few hours were wasted...). Doesn't it make sense to go through the steps explicitly?

1. Connect all event handlers
2. Assign `kwargs` to `@event.prop`s, letting events build up
3. Run `init()`on all widgets
4. Start event loop

Well, it's probably more complicated than that.. but it would be easier to understand if the flow was summarized like that somewhere in the docs.

**Comment by almarklein** [comment]
That's basically what happens. Though there are various subtleties, like first set the props to their initial value (without sending an event), then call init() (cause it might create stuff that handlers need), then fire all events. And do the same at the JS side, at the right moment, so that it works consistent with how the Py side works, and not get events all mixed up :)

But yes, it needs more docs and examples (#192). And this issue need fixed asap.

**Comment by almarklein** [comment]
(Sorry about your lost time, this is an issue that I have been wanting to fix since Scipy, have not gotten to it yet.)

**Comment by almarklein** [comment]
A good approach to fix this (IMO) is to emit an event at the moment that a handler connects to an event that corresponds to a property (instead of explicitly firing such events after init). That way, when any handler connects to a event corresponding to a property (at any time), it will immediately receive an "initializing" event.

Now, what to do with dynamism? If we connect to "children.*.count", should we (A) get an event for each child when children changes (because that will trigger a reconnect)? Or (B) should the initializing-property-event only happen when a handler initialized (not each time it registers)?

Remember #120? With (A), we basically have a proposal similar to that of @korijn; in connecting to "children.*.count", when children changes, you'd get an event for each child. Not entirely sure what's more natural, I fear that (A) might hurt performance in some cases.

**Comment by almarklein** [comment]
If you consider the case of "current_widget.title", then it makes a whole lot more sense to go with (A).

**Comment by Korijn** [comment]
It's hard to judge since I don't have a good sense of what the event lifecycle looks like. Let's see if I got this right:

1. Property-setters are called first, passing in the corresponding kwarg if available.
2. init() is called to construct the widget's internal hierarchy.
3. Event handlers are connected.

Now, I'm going to think out loud here, hoping that it'll produce something useful... I matched the "idea" labels to yours, correct me if I'm wrong.

(C) If you change the order to (3, 2, 1), the event handlers "naturally" get events for their initial values. The only downside is that init() can't assume that the properties have been set already.

(D) We could also change the order to (3, 1, 2), but then event handlers can't assume that the internal widget hierarchy has been set up.

(B) You can also emit "initial event" as a 4th step making the order (1,2,3,4). That could work. I don't really see a downside to this one?

(A) Your suggestion to emit an "initial event" whenever an event handler is connected sounds like a concept from the old react system. It would be more appropriate to call it a "current value event" IMHO. This would "automatically" make it work, but also introduce new behavior elsewhere, e.g. in dynamism, which seems undesirable to me. 

---

Aside of all this, I think that if you take a step back to zoom out, there is another solution that can be seen. Why not wait with step (4) until *all* event handlers have been attached, executing (4) globally instead of locally for each widget?

**Comment by Korijn** [comment]
Another idea: `@event.prop` decorates a property that emits events. When such a property is set, that causes an event to be emitted. Now, I assume that these are "collected" somewhere until the next event-loop iteration, since our event handlers have a `*events` argument. Why not change where they are collected?

Assuming that the initial page construction (of all widgets) occurs in a single event-loop iteration. If you let the events build up and collect them at the property, rather than at the connection/handler, they will automatically propagate to all connected handlers in the next event-loop iteration, no?

**Comment by almarklein** [comment]
> You can also emit "initial event" as a 4th step making the order (1,2,3,4). 

That's essentially what happens now. The problem is that a handler that connects after the object is created (as in a class that wraps another Widget) will not receive this event.

A global event is also not feasible, since you may compose / connect models after starting an app.

Just to be clear, I call it an "initialization-event" but it is the same event as would be send when the prop changes. I just called it that to make the distinction.

**Comment by almarklein** [comment]
> Your suggestion to emit an "initial event" whenever an event handler is connected sounds like a concept from the old react system. It would be more appropriate to call it a "current value event" IMHO. This would "automatically" make it work, but also introduce new behavior elsewhere, e.g. in dynamism, which seems undesirable to me. 

The name of the event is just for the sake of discussion. I think you should indeed see it as a "current value event". If what we chose changes the behavior, that will be alright if that behavior is more natural than what we have now :)

* It is clear that we want an initial event for handlers that connect to props on the same Model.
* This issue made clear that we also want such an initial event for handlers that connect to props of a wrapped model, because it would be confusing otherwise.
* Following through, I think it makes sense if *any* handler that connects (at any time) to a property receives an event to communicate the current value of that property. 

The remaining question, I think, is whether an automatic reconnect due to dynamism should also lead to such events. I am leaning towards yes. To clarify, for a connection "parent.title" or "children.*.count", we would receive "title" and "count" events when  the parent/children change. This is different from the (removed) behavior in #120, where we would get "children" and "parent" events (which the handler would then need to filter).

**Comment by Korijn** [comment]
Thanks for the clarification. I think you've got the right idea. I hope we're not overlooking any unexpected side-effects!

**Comment by almarklein** [comment]
The story continues ...

This was fixed by sending a special event when a handler *registered* to an event corresponding to a prop. A side effect of this is that a handler connecting to `children*.value` gets a new "value" event each time its children changes.

I just ran into an issue where `emit()` was used from `init()` which does not work anymore. And I think it *should* work. Inspired by something @Korijn said above, I made events be captured, and clear this captured cache of events *in the next event loop iteration*. Any handler connecting to an event in the current event loop iter will receive the cached events. This by itself would also solve the problem that this issue describes.

The question is now: should we get rid of the special behavior for events corresponding to properties? In other words, when we have a handler connected to "parent.stack.children.value":

* a `value` event is send when parent"

**Comment by Korijn** [comment]
Simpler seems better: it's more predictable.

If you want to respond to the amount of children changing, just add `parent.stack.children` to your connector!

Also, wouldn't it be `parent.stack.children.*.value`?

**Comment by Korijn** [comment]
Imagine using a deep connector `**` and getting events for all the elements/parents/children along the (many?) path! That's certainly undesired... I would definitely go with the simpler behavior.

**Comment by almarklein** [comment]
> Also, wouldn't it be `parent.stack.children.*.value`?

Yes, that was a typo.

> If you want to respond to the amount of children changing, just add `parent.stack.children` to your connector!

I agree with that, and I think it makes sense if you have a `*` in the connection string, . But if I think of an example where you want to keep of your parent's  title, I prefer writing `connect('parent.title')` and not `connect('parent', 'parent.title').

On the other hand, if Flexx re-sends events when the path changes, there is no way for the user to make Flexx not do that (unless he/she uses a proxy emitter or something). Whereas an extra connection string is easily added.

So I think we should go with the simpler approach yes.

**Comment by Korijn** [comment]
So I agree that we should prefer the simpler approach, although there may be a middle-ground too.

Consider the following: if you connect to `parent.title`, then when `parent` is switched out, that could mean that `parent.title` no longer has the same value as before the switch. In such a case, I think it would make sense if you receive an event. If the value remains the same however, what gives?

I think that with this subtle difference, you can have an intuitive development experience for both of the scenarios. Connecting to just `parent.title` should allow you to track any change in _the value_. The same is true for the deep connector. Because, IMHO, that's all the event handlers should really care about.

**Comment by almarklein** [comment]
I'm not sure if I understand what you mean. Checking if the value that `parent.title` represents changes when the parent changes seems like a lot of extra stuff: keeping track (holding on to) the current value, etc.. In that case I'd say we should not worry about sending an extra event when the value has not changed.

I don't see how what you propose maps to a connecting string with a star or with a deep connector, because then there is not a single value that you track. Rather, you're tracking a collection of values.

I'm almost inclined to say that we do the property-init-event thing only for connections that do not contain a star, but that would only add confusion.

Thinking about it more, a connection string is *not* a path to a value to track. It is a path to an event that we want to receive. This is obvious for stuff like mouse events, and also for the case where a connection string targets multiple events using the star syntax. It is less obvious for `parent.title`, but I don't think that case should break the rule.

We could consider allowing a syntax like `+parent.title` (exact syntax up for discussion) to indicate that the handler should fire for whenever any part in the path changes. Though let's wait with discussing this until we've used the new system for a bit.
