### ISSUE TITLE
event.connect to non-existent event: no error?

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#188]

**Comment by almarklein** [comment]
Ha! Or maybe I should say "bah" :)

I recently wondered about this myself, until I realized that it is the intended behavior; you can connect to an event of any name, and they will fire when `ob.emit('that_name', ...)` is called. There is not event-type checking. This is intended to make the event system easy and flexible.

But the fact that you and I both got confused by it is an indication that this might not be the best approach ...

Technically, it should be very easy to check that a handler connects to a known event. That means that the event must exist as a property, readonly or emitter on the class. But this is the case in almost all of our code, since we want events to be documented.

We can either:

* Keep as is, document better. Unless I am overlooking hard to overcome difficulties with the other solutions, I'd rather not do this.
* Force connecting to known event types in all Widgets.
* Force connecting to known event types always. Pretty profound change to the event system, but probably worth it.

**Comment by Korijn** [comment]
Another option:

* Log event firing/handling in such a way that it is easy to tell that an event is not being handled (related to #179)
