### ISSUE TITLE
Connection string micro language

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#194]
The connection string is already a powerful mechanism to connect to events. With dynamism, selection of all elements in a list, and in #172 deep selectors. Let's think of what we want the language to look like. How far do we want to take it. Are there any other useful features we could add?

I think the language should be simple and easy to remember. I don't think making it look like regexp is a good idea. Rather make it look more like Python. 
- We have paths / dynamism: `parent.title`, `foo.bar.spam.eggs`
- We have selecting all: was `children.*.value` -> new syntax per #172 is `children*.value`, could possibly also be `children[:].value`?
- In that line of thought we couls also allow `children[0].value` and `children[:-2].value`. I can hardly imagine a use-case though.
- Deep selectors: `children**.value`
- Optional selectors? `children.children?.value` looks either one or two levels deep.
- Force connection: if per #188 we will raise an error when connecting to an unknown event, `foo!` can be used to connect anyway.

cc @korijn @ivoflipse

**Comment by Korijn** [comment]
* Optional selectors are already supported, no? `children*.value, children.children*.value` is equivalent, I think.
* Force, as in, simply ignore the would-be error? -> Seems like an excellent idea. I would suggest putting the symbol at the start of the connection string though, rather than somewhere in the middle. E.g. `!foo.bar`.
* The use case for numerical selection of children will probably come around at some point. I like the syntax, anyhow.

Since we're in a micro language here, I think you should only use python-ish syntax when it's valid python syntax, to avoid confusion and bad assumptions. So, this is how I would expect it to work:

* `children*.value`
* `children**.value`
* `children[-1].value`
* `children[0].value`
* `children[:-1]*.value` (you always have to "unpack" collections, to be consistent)
* `children[:]**.value` -> this is equivalent to just `children**.value`

**Comment by almarklein** [comment]
> you always have to "unpack" collections, to be consistent

I'd say that if we go with a Python-looking `children[:].value`,  that the star is not needed. I kinda like that, but then how would we then write the deep selector? Maybe `deep(children[:]).value`. This is quickly starting to feel too complex IMO. It is a micro language, but maybe having it *not* look like Python is a virtue.

I suspect that optional selectors are not worth the effort; you can just write two connection strings in such cases. I have doubts about the usefulness of the index/slice selectors too. 

Let me phrase some options:

* A
  * `children[:].value` selects all children
  * `children[0].value` selects first child
  * `children[1:].value` selects all but first child
  * `children[:]+.value` selects all children and their children etc. (could also be a star, whatever)

* B
  * `children*.value` selects all children
  * `children**.value` selects all children and their children etc. (could also be a star, whatever)

* C (similar to B, but use a plus for deep selectors)
  * `children*.value` selects all children
  * `children*+.value` selects all children and their children etc. (could also be a star, whatever)
  * `foo+.value` deep-selection into the foo prop 

I lean slightly towards B or C, though I am starting to like `children[:].value` too.

**Comment by Korijn** [comment]
B looks the most predictable (and therefore easiest to use) to me.

I dislike `children[:].value` because _most Python developers will think_ that it is equivalent to `children.value`:

```python
>>> from collections import namedtuple                 
>>> Point = namedtuple('Point', ['x', 'y'])            
>>> points = [Point(i, i) for i in range(10)]          
>>> points[0].x                                        
0                                                      
>>> points.x                                           
Traceback (most recent call last):                     
  File "<stdin>", line 1, in <module>                  
AttributeError: 'list' object has no attribute 'x'     
>>> points[:].x                                        
Traceback (most recent call last):                     
  File "<stdin>", line 1, in <module>                  
AttributeError: 'list' object has no attribute 'x'     
```

However, in the micro-language, they aren't, although they resemble eachother very storngly, and that is IMO very confusing.

**Comment by almarklein** [comment]
We've been using the current form for quite a while now, and I think it works. I've tweaked it a little bit in #241 (the position of the exclamation mark moves to the end, so that all the "special stuff" is at the end).

The current rules will thus be:

* The string optionally has a label suffix separated by a colon. The label itself may consist of any chars.
* The string can have a "!" at the end to suppres warnings for connections to unknown event types. If the string has a label, the exclamation mark comes before it.
* Connection strings consist of parts separated by dots, thus forming a path. If an element on the path is a property, the connection will automatically reset when that property changes (a.k.a. dynamism).
* Each part can end with one star ('*'), indicating that the part is a list and that a connection should be made for each item in the list. 
* With two stars, the connection is made *recursively*, e.g. "children**"  connects to "children" and the children's children, etc.
* Stripped of '*', each part must be a valid identifier (ASCII).
