### ISSUE TITLE
PyScript: avoid garbage collection by avoiding anonymous function calls where they are not strictly necessary

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#288]
A performance bottleneck we've seen after working with PyScript for a while is hidden in list comprehensions and other inlined anonymous function calls.

In Python the syntax natively supports list comprehensions; PyScript transpiles these to inlined anonymous function calls. This creates a closure, which when used inside a loop, triggers garbage collection very frequently.

It seems to me that list comprehensions could also be transpiled to for loops, avoiding the memory- and garbage collection-overhead of closures.

Is this something that you see as feasible?

**Comment by almarklein** [comment]
This particular issue seems like relatively low hanging fruit to improve PyScript's performance. Certain list comprehensions can definitely be written as for-loops and other using `filter`, so making the parser smarted for list comprehension would definitely be feasible imo. Would also improve the readability BTW.

**Comment by Korijn** [comment]
Is an explicit if statement inside the loop not sufficient for the conditional part of the comprehension? I would think that using `filter` might also require a closure for the callable.

**Comment by almarklein** [comment]
mmm, I think you've got a point. I am not exactly sure about why I chose to use a closure. I think it made things easier, but this should definitely be revisited, and get rid of where possible.

**Comment by Korijn** [comment]
Adjusted the title to reflect our intent a little bit better.

This is a real performance issue for us; anytime we have a long-running loop with a closure in there, garbage collection comes along, blocking the UI thread for durations almost in the range of seconds.

**Comment by almarklein** [comment]
Looking into this now because they are a suspect in a memory leak (closures can easily create memory leaks if the function is not deleted).

The reason for writing this as a function is that multiple statements are needed to prep the data and write the for-loop itself, whereas its a single expression in Python. Its not trivial to determine where that code should be placed.

In assignments it is relatively easy:
```py
x = [i for i in range(10)]
# become effectively
x = []
for i in range(10):
    x.append(i)
```

But these cases are much harder though ...
```py
if foo() == [i for i**2 in range(4)]
```

Nevertheless, I found that the as it is now, the functions are *always* closures, because the iterator is read from the outer scope. We can improve this by passing it as an argument instead. This would make some functions just inner functions (not closures), but only if no other vars from the surrounding scope are used.
