### ISSUE TITLE
Q: code deployment on remote IPy notebook server

### ISSUE THREAD

**Issue by alexveden** [zoofIO/flexx#299]
I've created new custom widget component, and it works fine on my development localhost machine. But when I try to deploy this code on remote IPy Notebooks server the widget is drawn, but it doesn't respond to mouse clicks.

I'm seeing this in browser console:
> Socket connected
> Lost connection with server: Could not launch app: RuntimeError("Asked for app id 'UugOTCOcFDkadMCunJqq8hyg', but could not find it",) (1003)

I suspect that the problem is in the settings, and I need to make the server to listen remote hostname.
My setup is:
flexx: 0.4.1
Ubuntu 16.04
IPy Notebooks server: https://10.0.1.2:8888/

I've tried to add custom config file to ~/.config/.flexx.cfg and add following line to it:
> config.hostname=10.0.1.2

but it still has no effect.

p.s. Could you clarify generic .flexx.cfg paths locations for different OSes inside documentation, because it's not so intuitive to find 'appdata' in ~/.config in Linux?

Thx

**Comment by alexveden** [comment]
Changes, config contents to:
> hostname=10.0.1.2
and not it's connecting.

But another issue:
> The page at 'https://10.0.1.2:8888/notebooks/flexx_new.ipynb' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://10.0.1.2:49190/__default__/ws'. This request has been blocked; this endpoint must be available over WSS.

As I know there is no option to launch remote notebook server without HTTPS.

**Comment by almarklein** [comment]
A lot has changed w.r.t. notebook support since 0.4.1, though the latest issue seems to suggest that non-secure websockets are blocked. I have not looked into this in any way, but I suspect that you can make Flexx use `wss` by editing `flexx/app/_clientcore.py`.

I've added a note to the docs on how to find the appdata dir: ``flexx.util.config.appdata_dir()``. Putting it in `~/.config` was a suggestion from a Linux user who said it was the best place to put it (previously I used `~/.flexx`).

**Comment by almarklein** [comment]
I think the remaining problem is the issue of secure websockets, which is covered by #303, so closing this in favor of that issue.
