### ISSUE TITLE
Remote Jupyter server still doesn't work over HTTPS

### ISSUE THREAD

**Issue by alexveden** [zoofIO/flexx#316]
After PR https://github.com/zoofIO/flexx/pull/307 been merged I still have problems with remote notebook connections.

I've fixed this but I'm not able to create new pull request, can you help me with that?

**Comment by almarklein** [comment]
Sure! How familiar are you with git?

I tried to outline the general approach below, let me know if things are unclear of if you get stuck. A summary like this should probably be put on the wiki:

To get familiar with git, these are great starting points: 
* https://try.github.io
* https://git-scm.com/doc
* For specific questions: google it, its very likely that your question (and an answer) is on StackOverflow.
* You can always ask questions in the issue tracker or in the PR.

Setting things up:
* Create a fork of the repo that you want to contribute to, by clicking on the "fork" button on github. This will add a repo with the same name in your personal github account. 
* Make a clone of your fork on your local machine. In your fork, press the "clone or download" to get the command. My guess it will be `git clone https://github.com/alexveden/flexx.git`.
* Run `git remote add upstream https://github.com/zoofIO/flexx.git` so that you can easily update to the latest version.
* Add the directory that was just created to your `PYTHONPATH`, or use `pip install -e .` for an editable install; you can now make changes to the source and try them without needing a reinstall.

Making a change and pull request:
* First update to latest version: `git checkout master` followed by `git pull upstream master`.
* Create a new branch `git checkout -b my-branch-name`
* Make your changes
* After a piece of work is done, commit it: `git commit -am 'summary of made changes'`
* Optionally, make more changes, and commit them ...
* Push your commits to your fork `git push origin my-branch-name`
* In the github pages of your fork and the official Flexx repo you'll see a "create pull request" button.

Review process:
* Someone will probably request more changes.
* You commit and push changes as above, and they shall appear in the PR.
* Possibly, this is repeated ...
* When your PR is merged, update again: `git checkout master` followed by `git pull upstream master`.
* You can now delete your branch using `git branch -D my-branch-nam`.

**Comment by almarklein** [comment]
BW: if it's a small change confined to a single file, you can edit the file directly on Github and create a PR from there.

**Comment by almarklein** [comment]
Closed by #317
