### ISSUE TITLE
Assets only .js or .css?

### ISSUE THREAD

**Issue by jrversteegh** [zoofIO/flexx#347]
Is there a reason why assets can only be .js or .css?
I ask because leaflet.css references a few png images. I guess that's not uncommon. Adding the images as shared data will break the link that is relative to the css.

**Comment by almarklein** [comment]
Images used to be assets too, but they were separated because JS and CSS requires a different code path, because they are injected into the page, while images should just be served and the browser will pick them up. 

I think that you're now running into a new situation where your css file needs a png file to be relative to itself. 

I am assuming this is related to the leaflet functionality? If we (start with) using the on-line version of leaflet, than it should work, right? Because Flexx wont touch these assets.

**Comment by jrversteegh** [comment]
Yes, I ran into it with leaflet, but this seems to me like a common case. I am fairly sure I've seen it before. However, I am not a web developer.
Using leaflet online is not an option for me because my application will be offline. I guess I'll be able to work around this somehow. Simplest would probably be to just patch the css. Not pretty, but it'll work. 
Anyway, thanks for explaining why it's only js and css.

**Comment by jrversteegh** [comment]
Btw, what do you mean by "using the on-line version"? I haven't been able to figure out how to do that apart maybe from injecting raw html by setting node.innerHTML somewhere (which I haven't tried).

**Comment by almarklein** [comment]
I mean to use CDN (or however leaflet is hosted) in the same way that the jquery and code editor examples work. But if you really want to make it work without an internet connection, we'd have to see how to make it work. Patching the CSS is indeed a good solution to make it work short term, to get this new functionality going. But maybe we'll have to provide a proper solution at some point.

I wonder though, in this case perhaps the png is assumed to be right "next" to the css file (as in, in the same directory), but other use-cases can assume a different relative path, in which case patching the CSS is inevitable. So perhaps the CSS is not even that bad a solution.

**Comment by jrversteegh** [comment]
There are a few issues:

- The css in the code_editor_cm example gets inlined, just like phospor, so that doesn't work. The only difference appears to be that phosphor gets permanently downloaded into the "resources" directory. 
- I still  get the same complaint about the .png not being .css or .js.
- Official online source for leaflet is unpkg.com, which requires a User-Agent to be set (see your comment on the earlier leaflet pull request), however I did find a version on CDN as well, so that is avoidable.

It would make sense to be able to use a remote asset without having it inlined. This may be possible (the "link" parameter in `Asset.to_html` suggests it), but I haven't found out how. The code_editor_cm example doesn't appear to do it.

**Comment by almarklein** [comment]
Oh, you're right. The CSS and JS get inlined even though they are a remote (http) asset, because the assets are loaded just-in-time, and then using a link would make it available too late ...  It has other advantages, such as that things also work in the notebook, in Jupyterlab, and even in exported notebooks. But in this particular case this means we need to do some extra work. I'm looking into it now. Will get back shortly.

I'm ok with adding the user-agent part regardless, which would make it possible to use the official resources, though indeed, more work is needed to make this work.

**Comment by almarklein** [comment]
This should work:
```
def get_leaflet_css():
    from urllib.request import Request, urlopen
    url = 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css'
    code = urlopen(url).read().decode()
    code = code.replace('images/', 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/images/')
    return code
    
# app.assets.associate_asset(__name__, 'https://unpkg.com/leaflet@1.0.3/dist/leaflet.css')
# app.assets.associate_asset(__name__, 'https://unpkg.com/leaflet@1.0.3/dist/leaflet.js')
app.assets.associate_asset(__name__, 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.js')
app.assets.associate_asset(__name__, 'leaflet.css', get_leaflet_css)
```

To make it work with the original leaflet host, you can set the useragent as you did earlier, but you'd also need to apply a similar change in `Asset._get_from_url()` in `flexx/app/_asset.py`. The inlined css seems correct this way, though it does not show a map for me yet, I'm assuming Im doing something wrong.

We can eventually have a look at how to make this work off-line, but we'll have to have a good look at how to store and provide the png images.

**Comment by jrversteegh** [comment]
Thanks!

See [https://github.com/jrversteegh/flexx/blob/add_leaflet_example/flexx/ui/examples/leaflet.py] for a working map. 
I will modify that with your above code later.

**Comment by almarklein** [comment]
That looks great!
