### ISSUE TITLE
Use of existing Python-JavaScript tools such as Brython?

### ISSUE THREAD

**Issue by pya** [zoofIO/flexx#4]
This looks like a great project. Looking forward to using it. Just one question. Have you considered using something like [Brython] (http://www.brython.info/) for the JavaScript handling instead of writing your own implementation? Having a Python3-only solutions seems fine to me. Do you want to avoid too many dependency? Or does Brython not meet your needs?

**Comment by almarklein** [comment]
Hi Mike,

Flexx is designed to be a Python library, that really only uses JS as a "runtime" to draw its UI. The PyScript (Python code that gets converted to JS) that you can use in Flexx is really just JavaScript with a Python syntax (similar to Coffeescript and RapidScript).

We *could* use Brython on the JS side to allow "real Python code". But in addition to being a dependencie, Brython is quite heavy and relatively slow, because it tries so hard to be real Python (e.g. with exceptions behaving in the same way). 

Further, I would like the PyScript code to be able to interface with other JS libs. When using a Python "runtime" such as Brython, you also lose that interaction (or at least make harder/awkward).

For the record: The PyScipt converter is based on/inspired by existing code from another project, which helped a lot.

**Comment by pya** [comment]
Hi Almar,

Thanks for your answer. Obviously, you did a sound research for options and alternatives. Sometimes rolling your own is better than re-using existing libraries. This project seems to fall into this category. Looking forward to your talk in Cambridge.

**Comment by almarklein** [comment]
PyScript is now a bit more Pythonic. Enough to run PyStone. Here are some results: https://github.com/zoofIO/flexx/blob/master/examples/app/benchmark.py#L10-L17  This shows that the approach of PyScript has significant advantages compared to Brython et al. in terms of performance (and its JS should also be much smaller).
